services:
  backend:
    container_name: poi-service-backend
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        - LOCATION=Hamburg # Fetch POIs for Hamburg
    volumes:
      - .:/code
    environment:
      - DJANGO_DEBUG_MODE=True
    networks:
      - network
    ports:
      - "8000:8000" # web server
    command: ./run-dev.sh
    restart: unless-stopped

networks:
  network:
