# Generated by Django 4.2.11 on 2024-04-15 07:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoiLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('line', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Line of points of interest',
                'verbose_name_plural': 'Lines of points of interest',
            },
        ),
    ]
