# Generated by Django 4.2.11 on 2024-07-02 08:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pois', '0002_poiline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('type', models.TextField()),
                ('coordinate', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Landmark',
                'verbose_name_plural': 'Landmarks',
            },
        ),
    ]
